### ISSUE TITLE
Jekyll 2.5 default host is not compatible with docker when serving

### ISSUE THREAD

**Issue by robink** [grahamc/docker-jekyll#18]
In Jekyll 2.5, default host is now `127.0.0.1`

> Changelog
> Use 127.0.0.1 as default host instead of 0.0.0.0 ([#3053](https://github.com/jekyll/jekyll/pull/3053))

This host won't work with the current docker. The launch command need to be updated to the following:

`sudo docker run -d --rm -v "$PWD:/src" -p 4000:4000 grahamc/jekyll serve -H 0.0.0.0`

**Comment by WalterInSH** [comment]
+1

**Comment by grahamc** [comment]
Ah yes! Sorry. I will edit the docs.

**Comment by grahamc** [comment]
Fixed here: https://github.com/grahamc/docker-jekyll/commit/24d55fd0f94caf6b3ecaea6f0159b417ec68bcfc

**Comment by grahamc** [comment]
Thank you for bringing this to my attention!
