### ISSUE TITLE
Proposal: Create a web-oriented variant

### ISSUE THREAD

**Issue by funkyfuture** [grahamc/docker-jekyll#25]
we use this image to directly serve pages to the web. however we need to apply some changes to make it listen to port 80.

i suggest to add an image with `:web`-tag that includes these changes. if you approve, i will provide a patch.

**Comment by ghost** [comment]
Here's an example [Dockerfile for Jekyll](https://gist.github.com/jhabdas/e0d5e3bed0316f1a5783) which requires no config once built to serve HTTP traffic in dev or prod at scale. Seems like the way to go so builds remain straightforward IMHO. Thoughts?

**Comment by funkyfuture** [comment]
my thought is that i aimed at something much more simpler. it's about the listening-port, and that's a matter of an invokation-option.
